<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Local extends \Entities\Local implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setCodeLocal($codeLocal)
    {
        $this->__load();
        return parent::setCodeLocal($codeLocal);
    }

    public function getCodeLocal()
    {
        $this->__load();
        return parent::getCodeLocal();
    }

    public function setEtage($etage)
    {
        $this->__load();
        return parent::setEtage($etage);
    }

    public function getEtage()
    {
        $this->__load();
        return parent::getEtage();
    }

    public function setSurface($surface)
    {
        $this->__load();
        return parent::setSurface($surface);
    }

    public function getSurface()
    {
        $this->__load();
        return parent::getSurface();
    }

    public function setNlocal($nlocal)
    {
        $this->__load();
        return parent::setNlocal($nlocal);
    }

    public function getNlocal()
    {
        $this->__load();
        return parent::getNlocal();
    }

    public function setNomlocataire($nomlocataire)
    {
        $this->__load();
        return parent::setNomlocataire($nomlocataire);
    }

    public function getNomlocataire()
    {
        $this->__load();
        return parent::getNomlocataire();
    }

    public function setNonBatis($nonBatis)
    {
        $this->__load();
        return parent::setNonBatis($nonBatis);
    }

    public function getNonBatis()
    {
        $this->__load();
        return parent::getNonBatis();
    }

    public function setBatis($batis)
    {
        $this->__load();
        return parent::setBatis($batis);
    }

    public function getBatis()
    {
        $this->__load();
        return parent::getBatis();
    }

    public function setUsage($usage)
    {
        $this->__load();
        return parent::setUsage($usage);
    }

    public function getUsage()
    {
        $this->__load();
        return parent::getUsage();
    }

    public function setNatureLocataire($natureLocataire)
    {
        $this->__load();
        return parent::setNatureLocataire($natureLocataire);
    }

    public function getNatureLocataire()
    {
        $this->__load();
        return parent::getNatureLocataire();
    }

    public function setValeurLocation($valeurLocation)
    {
        $this->__load();
        return parent::setValeurLocation($valeurLocation);
    }

    public function getValeurLocation()
    {
        $this->__load();
        return parent::getValeurLocation();
    }

    public function setNomFamilleOccupant($nomFamilleOccupant)
    {
        $this->__load();
        return parent::setNomFamilleOccupant($nomFamilleOccupant);
    }

    public function getNomFamilleOccupant()
    {
        $this->__load();
        return parent::getNomFamilleOccupant();
    }

    public function setCuisineInde($cuisineInde)
    {
        $this->__load();
        return parent::setCuisineInde($cuisineInde);
    }

    public function getCuisineInde()
    {
        $this->__load();
        return parent::getCuisineInde();
    }

    public function setSalleEau($salleEau)
    {
        $this->__load();
        return parent::setSalleEau($salleEau);
    }

    public function getSalleEau()
    {
        $this->__load();
        return parent::getSalleEau();
    }

    public function setAccessibilite($accessibilite)
    {
        $this->__load();
        return parent::setAccessibilite($accessibilite);
    }

    public function getAccessibilite()
    {
        $this->__load();
        return parent::getAccessibilite();
    }

    public function setEclairageN($eclairageN)
    {
        $this->__load();
        return parent::setEclairageN($eclairageN);
    }

    public function getEclairageN()
    {
        $this->__load();
        return parent::getEclairageN();
    }

    public function setSurfaceHabituelleNC($surfaceHabituelleNC)
    {
        $this->__load();
        return parent::setSurfaceHabituelleNC($surfaceHabituelleNC);
    }

    public function getSurfaceHabituelleNC()
    {
        $this->__load();
        return parent::getSurfaceHabituelleNC();
    }

    public function setMoyenChauffage($moyenChauffage)
    {
        $this->__load();
        return parent::setMoyenChauffage($moyenChauffage);
    }

    public function getMoyenChauffage()
    {
        $this->__load();
        return parent::getMoyenChauffage();
    }

    public function setVentillation($ventillation)
    {
        $this->__load();
        return parent::setVentillation($ventillation);
    }

    public function getVentillation()
    {
        $this->__load();
        return parent::getVentillation();
    }

    public function setHumidite($humidite)
    {
        $this->__load();
        return parent::setHumidite($humidite);
    }

    public function getHumidite()
    {
        $this->__load();
        return parent::getHumidite();
    }

    public function setDistEau($distEau)
    {
        $this->__load();
        return parent::setDistEau($distEau);
    }

    public function getDistEau()
    {
        $this->__load();
        return parent::getDistEau();
    }

    public function setEvacC($evacC)
    {
        $this->__load();
        return parent::setEvacC($evacC);
    }

    public function getEvacC()
    {
        $this->__load();
        return parent::getEvacC();
    }

    public function setImmeuble(\Entities\Immeuble $immeuble = NULL)
    {
        $this->__load();
        return parent::setImmeuble($immeuble);
    }

    public function getImmeuble()
    {
        $this->__load();
        return parent::getImmeuble();
    }

    public function setUsag($usag)
    {
        $this->__load();
        return parent::setUsag($usag);
    }

    public function getUsag()
    {
        $this->__load();
        return parent::getUsag();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'Code_Local', 'Etage', 'Surface', 'Nlocal', 'Nomlocataire', 'NonBatis', 'Batis', 'Usag', 'NatureLocataire', 'ValeurLocation', 'NomFamilleOccupant', 'CuisineInde', 'SalleEau', 'Accessibilite', 'EclairageN', 'SurfaceHabituelleNC', 'MoyenChauffage', 'Ventillation', 'Humidite', 'DistEau', 'EvacC', 'Immeuble');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}