<?php

namespace Proxies\__CG__\Entities;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class Etat extends \Entities\Etat implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setEntree($entree)
    {
        $this->__load();
        return parent::setEntree($entree);
    }

    public function getEntree()
    {
        $this->__load();
        return parent::getEntree();
    }

    public function setPartieCom($partieCom)
    {
        $this->__load();
        return parent::setPartieCom($partieCom);
    }

    public function getPartieCom()
    {
        $this->__load();
        return parent::getPartieCom();
    }

    public function setPartieMure($partieMure)
    {
        $this->__load();
        return parent::setPartieMure($partieMure);
    }

    public function getPartieMure()
    {
        $this->__load();
        return parent::getPartieMure();
    }

    public function setPartieBalcon($partieBalcon)
    {
        $this->__load();
        return parent::setPartieBalcon($partieBalcon);
    }

    public function getPartieBalcon()
    {
        $this->__load();
        return parent::getPartieBalcon();
    }

    public function setTerras($terras)
    {
        $this->__load();
        return parent::setTerras($terras);
    }

    public function getTerras()
    {
        $this->__load();
        return parent::getTerras();
    }

    public function setPlaton($platon)
    {
        $this->__load();
        return parent::setPlaton($platon);
    }

    public function getPlaton()
    {
        $this->__load();
        return parent::getPlaton();
    }

    public function setEvacuation($evacuation)
    {
        $this->__load();
        return parent::setEvacuation($evacuation);
    }

    public function getEvacuation()
    {
        $this->__load();
        return parent::getEvacuation();
    }

    public function setElectrique($electrique)
    {
        $this->__load();
        return parent::setElectrique($electrique);
    }

    public function getElectrique()
    {
        $this->__load();
        return parent::getElectrique();
    }

    public function setGaz($gaz)
    {
        $this->__load();
        return parent::setGaz($gaz);
    }

    public function getGaz()
    {
        $this->__load();
        return parent::getGaz();
    }

    public function setEau($eau)
    {
        $this->__load();
        return parent::setEau($eau);
    }

    public function getEau()
    {
        $this->__load();
        return parent::getEau();
    }

    public function setEtageB($etageB)
    {
        $this->__load();
        return parent::setEtageB($etageB);
    }

    public function getEtageB()
    {
        $this->__load();
        return parent::getEtageB();
    }

    public function setEtageM($etageM)
    {
        $this->__load();
        return parent::setEtageM($etageM);
    }

    public function getEtageM()
    {
        $this->__load();
        return parent::getEtageM();
    }

    public function setEtageR($etageR)
    {
        $this->__load();
        return parent::setEtageR($etageR);
    }

    public function getEtageR()
    {
        $this->__load();
        return parent::getEtageR();
    }

    public function setEtageMC($etageMC)
    {
        $this->__load();
        return parent::setEtageMC($etageMC);
    }

    public function getEtageMC()
    {
        $this->__load();
        return parent::getEtageMC();
    }

    public function setNbrBienB($nbrBienB)
    {
        $this->__load();
        return parent::setNbrBienB($nbrBienB);
    }

    public function getNbrBienB()
    {
        $this->__load();
        return parent::getNbrBienB();
    }

    public function setNbrBienM($nbrBienM)
    {
        $this->__load();
        return parent::setNbrBienM($nbrBienM);
    }

    public function getNbrBienM()
    {
        $this->__load();
        return parent::getNbrBienM();
    }

    public function setNbrBienR($nbrBienR)
    {
        $this->__load();
        return parent::setNbrBienR($nbrBienR);
    }

    public function getNbrBienR()
    {
        $this->__load();
        return parent::getNbrBienR();
    }

    public function setNbrBienMC($nbrBienMC)
    {
        $this->__load();
        return parent::setNbrBienMC($nbrBienMC);
    }

    public function getNbrBienMC()
    {
        $this->__load();
        return parent::getNbrBienMC();
    }

    public function setImmeuble(\Entities\Immeuble $immeuble = NULL)
    {
        $this->__load();
        return parent::setImmeuble($immeuble);
    }

    public function getImmeuble()
    {
        $this->__load();
        return parent::getImmeuble();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'Entree', 'PartieCom', 'PartieMure', 'PartieBalcon', 'Terras', 'Platon', 'Evacuation', 'Electrique', 'Gaz', 'Eau', 'EtageB', 'EtageM', 'EtageR', 'EtageMC', 'NbrBienB', 'NbrBienM', 'NbrBienR', 'NbrBienMC', 'Immeuble');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}